# Introduction {#intro}


What does a statistical paper looks like? As all scientific papers, it should
have some commonly expected structures which include components such as title,
abstract, keywords, introduction, methods, results, discussion,
acknowledgements, references, appendix, and supplement. Due to the
specificity of the statistical discipline and application areas, however,
statistical papers could look quite different one from another. 


There are different types of statistical papers. A theory paper would look
similar to a paper in mathematics, with statement of the problem, presentation
of some theorems, and technical proofs. Such papers are not covered by here. We
focus on two types of statistical papers: application papers and method papers.
Application papers focus on a specific application problem in a certain domain
where the research discoveries depend on applications of existing or novel
statistical methods. Method papers, on the other hand, aim to provide a general
methodological solution to a class of applied problems. Often times, methods
paper have a theoretical component, for example, the establishment of the
asymptotic properties of a new estimator. An applied paper in statistics could
be a method paper in the domain of the problem it solves.


An author should always keep the target audience in mind when writing. There are
many statistical journals on the wide spectrum for applied to theoretical
papers. Each one has its own aims and scope, with different target
readerships. Writings such as customary statistical reports that are not
intended for journal publications also have target readerships. Regardless of
the audience, any scientific paper should be convincing and concise. You need to
show the readers that your work is important, valid, and useful. You don't want
to waste the time of any readers.


## Applied papers

An applied paper has a widely accepted structure:

+ Introduction
+ Data description
+ Methods
+ Results
+ Discussion

An applied paper can be applying existing statistical methods to solve an
applied problem. See, for example, @price2021effects; @caplan2019dental.


When sensitivity analysis is desired for the applications, one can have a
section on simulation studies. See, for example, @jiao2022cyberattack;
li2021uncertainty.


Some applied papers can involve novel methodology development that is motivated
by an applied problem. In such cases, simulation studies become necessary, where
you validate your methods with simulated data so you can check your estimator
with the truth. Such check is not feasible when analyzing real data.
See, for example, @jiao2021bayesian; @hu2021moving.

## Methods papers

A methods paper focuses on a novel method that is applicable to a general class
of problems arising in different domains. A commonly seen structure is:

+ Introduction
+ Methods (e.g., estimation, hypothesis tests, diagnosis)
+ Properties
+ Simulations
+ Illustrations (with real applications)
+ Discussion/Conclusions.


Here are some examples: @li2022regularized; @lau2021bias.



<!-- You can label chapter and section titles using `{#label}` after them, e.g., we can reference Chapter \@ref(intro). If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \@ref(methods). -->

<!-- Figures and tables with captions will be placed in `figure` and `table` environments, respectively. -->

<!-- ```{r nice-fig, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'} -->
<!-- par(mar = c(4, 4, .1, .1)) -->
<!-- plot(pressure, type = 'b', pch = 19) -->
<!-- ``` -->

<!-- Reference a figure by its code chunk label with the `fig:` prefix, e.g., see Figure \@ref(fig:nice-fig). Similarly, you can reference tables generated from `knitr::kable()`, e.g., see Table \@ref(tab:nice-tab). -->

<!-- ```{r nice-tab, tidy=FALSE} -->
<!-- knitr::kable( -->
<!--   head(iris, 20), caption = 'Here is a nice table!', -->
<!--   booktabs = TRUE -->
<!-- ) -->
<!-- ``` -->

<!-- You can write citations, too. For example, we are using the **bookdown** package [@R-bookdown] in this sample book, which was built on top of R Markdown and **knitr** [@xie2015]. -->
