# Review a Paper

Peer review is the system used to assess the quality of a manuscript before it 
is published in a journal. 

Independent researchers in the relevant research area assess submitted 
manuscripts for originality, validity and significance to help editors determine
whether a manuscript should be published in their journal.

Reviewing is the other side of the same coin as writing. It is an important
skill and service for the scientific community. A good writer anticipates
comments from possible reviewers and addresses them in writing. A critical 
review helps make a manuscript much stronger.

According to <https://www.biomedcentral.com/getpublished/peer-review-process>,

> Peer review is an integral part of scientific publishing that confirms the
> validity of the manuscript. Peer reviewers are experts who volunteer their 
> time to help improve the manuscripts they review. By undergoing peer review, 
> manuscripts should become:
>
> More robust - peer reviewers may point out gaps in a paper that require more
> explanation or additional experiments.
> 
> Easier to read - if parts of your paper are difficult to understand, reviewers 
> can suggest changes.
> 
> More useful - peer reviewers also consider the importance of your paper to 
> others in your field.

In this writing course, we are writing statistical projects. Here is a check
list adapted from <https://www.science.org/content/article/how-review-paper>.

+ Are the background literature and study rationale clearly articulated?
+ Do the hypotheses follow logically from previous work?
+ Are the statistical methods appropriate?
+ Are the methods robust and well controlled?
+ Is the statistical notation clearly defined?
+ Were the statistical methods conducted correctly?   
+ Are the assumptions of the statistical methods clearly articulated?
+ Are the assumptions of the statistical methods satisfied?
+ Is the presentation of results clear and accessible? 
+ To what extent does the Discussion place the findings in a wider context and
  achieve a balance between interpretation and useful speculation versus tedious
  waffling?


To write a reviewer's report, here is a template.

+ A summary of the what the paper is about and how you feel about its solidity.
+ List the major concerns in detail about the paper eluded in the summary.
+ Go through the specific points that are not clearly presented or need to be
  improved, in the order they appeared in the paper.
+ Finally, a list of really minor stuff (misprints, notation abuse, etc.).


Tips:

+ Precisely identify the location of the concern (page number, line number,
  section number, etc.)
+ Be as constructive as possible.
+ Avoid rude or disparaging remarks.
+ Back up major criticisms.
+ Make the review useful for the editor as well as for the authors.

