on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: Quarto book

jobs:
  quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: quarto-${{ github.event_name != 'pull_request' || github.run_id }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render book
        run: make render

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
